In [1]:
import numpy as np

# Creating a random vector of size 15 with integers of range 1-20
random_vector = np.random.randint(low=1, high=21, size=15)

# Reshaping the vector to 3 by 5 array
array_3x5 = random_vector.reshape(3, 5)
print(array_3x5)

# Printing the shape of the array
print(array_3x5.shape)

# Replacing the max in each row by 0
array_3x5[np.arange(3), array_3x5.argmax(axis=1)] = 0

# Printing the modified array
print(array_3x5)

[[ 2 19 17 10  9]
 [ 8  2  6 16 11]
 [15  2  9  4  9]]
(3, 5)
[[ 2  0 17 10  9]
 [ 8  2  6  0 11]
 [ 0  2  9  4  9]]


In [2]:
import numpy as np

# Create a 2-dimensional array
array_2d = np.zeros((4, 3), dtype=np.int32)

# Print the array
print("Array:")
print(array_2d)

# Print shape, type, and data type
print("\nShape:", array_2d.shape)
print("Type:", type(array_2d))
print("Data Type:", array_2d.dtype)


Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


In [3]:
import numpy as np

# Defining the input matrix
A = np.array([[3, -2], [1, 0]])

# Computing the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Printing the results
print("Eigenvalues: ", eigenvalues)
print("Right eigenvectors:\n", eigenvectors)


Eigenvalues:  [2. 1.]
Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
import numpy as np

# Defining the input array
A = np.array([[0, 1, 2], [3, 4, 5]])

# Computing the sum of the diagonal elements
diag_sum = np.trace(A)

# Printing the result
print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [5]:
import numpy as np

# Defining the input array
A = np.array([[1, 2], [3, 4], [5, 6]])

# Reshaping the array to a 2x3 shape without changing its data
B = A.reshape((2, 3))

# Printing the original and reshaped arrays
print("Original array:\n", A)
print("Reshaped array:\n", B)

Original array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
